---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arlepton-generator
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: arlepton-generator
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
        release: {{ .Release.Name }}
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/opaque-ports: "3000 80"
    spec:
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: "Always"
        name: arlepton-generator
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
