---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generator-gen
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generator-down
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: default
