---
apiVersion: v1
kind: Service
metadata:
  name: arlepton-generator-svc
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
