apiVersion: v1
kind: ConfigMap
metadata:
  name: generator-keycloak-cm
  labels:
    app: generator
    group: arlepton
data:
  keycloak.json: |-
    {
        "clientId": "generator",
        "bearerOnly": true,
        "serverUrl": "https://api.arlepton.com/auth/",
        "realm": "arlepton",
        "credentials": {
            "secret": "e7c060bc-a667-48f5-a5f9-e1f916982cc3"
        }
    }
