---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  labels:
    app: generator
    group: arlepton
spec:
  selector:
    matchLabels:
      app: generator
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: generator
        group: arlepton
    spec:
      imagePullSecrets:
      - name: registry-pull
      containers:
      - name: generator
        image: arphoenix.azurecr.io/arlepton/generator:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: ENV
            value: production
          - name: PORT
            value: "3000"
        volumeMounts:
          - name: keycloak-config
            mountPath: /app/json
            readOnly: true
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
          - name: keycloak-config
            configMap:
              name: generator-keycloak-cm
