---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quasar-spawn
  namespace: quasar
spec:
  selector:
    matchLabels:
      app: quasar-spawn
  template:
    metadata:
      labels:
        app: quasar-spawn
    spec:
      imagePullSecrets:
      - name: registry-pull
      containers:
      - name: quasar-spawn
        image: registry.quasarbot.com/quasar/quasar-spawn:0.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: ENV
            value: production
          - name: PORT
            value: "3000"
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 192Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - st-louis-01