logging:
  level:
    <%= packageRoot %>: DEBUG
    org.springframework.boot.context: DEBUG
server:
  compression:
    enabled: true
  port: <%=portNumber%>
  servlet: 
    context-path: /<%=artifact%><% if (swagger) { %>
springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
    info:
      title: 
      description: <%= appTitle %> Docs.
      version: 1.0
    base-package: <%= packageRoot %><% } %><% if (actuator || metricsinflux) { %>
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'<% } if (metricsinflux) { %>
  metrics:
    export:
      influx:
        db: <%=artifact%>
        uri: http://localhost:8086<% } %>
spring:
  messages:
    basename: i18n/messages<% if (redis) { %>
  cache:
    type: redis<% } if (mongo) { %>
  data:
    mongodb:
      host: localhost
      port: 27017
      database: <%=artifact%>
      authenticationDatabase: <%=artifact%>
      username: <%=artifact%>
      password: <%=randomPasswd%><% } if (redis) { %>
  redis:
    host: localhost
    port: 6379<% } if (postgres) { %>
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: <%=randomPasswd%>
    continue-on-error: true<% } if (oracle) {%>
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    continue-on-error: true<% } if (jpa) { %>
  jpa:
    hibernate:
      ddl-auto: update
    database: <%=databaseJpa%>
    database-platform: org.hibernate.dialect.<%=databaseDialect%>
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true<% } if (rabbit) { %>
  rabbitmq:
    host: localhost
    port: 5672
    username: <%=artifact%>
    password: <%=randomPasswd%>
    virtual-host: /
    connection-timeout: 9000<% } if (cloud) { %>
  cloud:
    stream:<% if (kafka) { %>
      defaultBinder: business
      binders:
        business:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      autoAddPartitions: true
                      brokers: 127.0.0.1:9092
                      zkNodes: 127.0.0.1:2181<% } %>
      bindings:
        <%=artifact%>_output:
          destination: <%=artifact%>-output
          contentType: application/json
          producer:
            headerMode: none
        <%=artifact%>_input:
          destination: <%=artifact%>-input
          contentType: application/json
          consumer:
            maxAttempts: 3
            headerMode: none<% } if (mqtt) { %>
<%=artifact%>:
  messages:
    output-queue: <%=artifact%>/output
    input-queue: <%=artifact%>/input
  mqtt:
    automaticReconnect: true
    cleanSession: true
    connectionTimeout: 10
    clientId: <%=artifact%>-client-mqtt
    hostname: 127.0.0.1
    port: 1883<% } if (keycloak) { %>
keycloak:
  realm: <%=kcRealm%>
  auth-server-url: <%=kcUrl%>
  ssl-required: external
  resource: <%=kcClientId%>
  bearer-only: true
  credentials:
    secret: <%=kcClientSecret%> 
  security-constraints:
  - auth-roles:
    - devops
    security-collections:
    - name: 
      patterns:
      - /* 
<% } %>
