---
apiVersion: v1
kind: Service
metadata:
  name: <%=artifactId%>-svc
  labels:
    app: <%=artifactId%>
    stack: generator
spec:
  type: ClusterIP
  selector:
    app: <%=artifactId%>
  ports:
    - port: 80
      targetPort: <%=port%>
