---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%=artifactId%>-ing
  labels:
    app: <%=artifactId%>
    stack: spawn
spec:
  rules:
  - host: <%=k8s.ingressHost%>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <%=artifactId%>-svc
            port: 
              number: 80
